### ISSUE TITLE
Exception when scanning in Black and White

### ISSUE THREAD

**Issue by xM8WVqaG** [cyanfish/naps2#127]
**Describe the bug**

When attempting to scan in B&W NAPS2 errors.

```
System.Exception: System.ArgumentException: SubPixelType.InvertedBit is only supported when both source and destination are 1 bit per pixel
   at NAPS2.Images.Bitwise.CopyBitwiseImageOp.ValidateCore(BitwiseImageData src, BitwiseImageData dst) in /run/build/main/NAPS2.Images/Bitwise/CopyBitwiseImageOp.cs:line 53
   at NAPS2.Images.Bitwise.BinaryBitwiseImageOp.ValidateAndPerform(BitwiseImageData src, BitwiseImageData dst) in /run/build/main/NAPS2.Images/Bitwise/BinaryBitwiseImageOp.cs:line 59
   at NAPS2.Images.Bitwise.BinaryBitwiseImageOp.Perform(Byte[] src, PixelInfo srcPixelInfo, IMemoryImage dst) in /run/build/main/NAPS2.Images/Bitwise/BinaryBitwiseImageOp.cs:line 37
   at NAPS2.Scan.Internal.Sane.SaneScanDriver.ProcessSingleFrameImage(SaneReadParameters p, Byte[] data) in /run/build/main/NAPS2.Sdk/Scan/Internal/Sane/SaneScanDriver.cs:line 222
   at NAPS2.Scan.Internal.Sane.SaneScanDriver.ScanPage(SaneDevice device, IScanEvents scanEvents) in /run/build/main/NAPS2.Sdk/Scan/Internal/Sane/SaneScanDriver.cs:line 207
   at NAPS2.Scan.Internal.Sane.SaneScanDriver.<>c__DisplayClass10_0.<Scan>b__0() in /run/build/main/NAPS2.Sdk/Scan/Internal/Sane/SaneScanDriver.cs:line 96
   at System.Threading.Tasks.Task.InnerInvoke()
   at System.Threading.Tasks.Task.<>c.<.cctor>b__272_0(Object )
   at System.Threading.ExecutionContext.RunFromThreadPoolDispatchLoop(Thread , ExecutionContext , ContextCallback , Object )
--- End of stack trace from previous location ---
   at System.Threading.ExecutionContext.RunFromThreadPoolDispatchLoop(Thread , ExecutionContext , ContextCallback , Object )
   at System.Threading.Tasks.Task.ExecuteWithThreadLocal(Task& , Thread )
--- End of stack trace from previous location ---
   at NAPS2.Scan.Internal.RemoteScanController.Scan(ScanOptions options, CancellationToken cancelToken, IScanEvents scanEvents, Action`2 callback) in /run/build/main/NAPS2.Sdk/Scan/Internal/RemoteScanController.cs:line 40
   at NAPS2.Remoting.Worker.WorkerServiceImpl.Scan(ScanRequest request, IServerStreamWriter`1 responseStream, ServerCallContext context) in /run/build/main/NAPS2.Sdk/Remoting/Worker/WorkerServiceImpl.cs:line 151
   at NAPS2.Remoting.RemotingHelper.HandleErrors(Error error) in /run/build/main/NAPS2.Sdk/Remoting/RemotingHelper.cs:line 24
   at NAPS2.Remoting.Worker.WorkerServiceAdapter.Scan(ScanningContext scanningContext, ScanOptions options, CancellationToken cancelToken, IScanEvents scanEvents, Action`2 imageCallback) in /run/build/main/NAPS2.Sdk/Remoting/Worker/WorkerServiceAdapter.cs:line 83
   at NAPS2.Scan.Internal.WorkerScanBridge.Scan(ScanOptions options, CancellationToken cancelToken, IScanEvents scanEvents, Action`2 callback) in /run/build/main/NAPS2.Sdk/Scan/Internal/WorkerScanBridge.cs:line 38
   at NAPS2.Scan.ScanController.<>c__DisplayClass13_0.<<Scan>b__6>d.MoveNext() in /run/build/main/NAPS2.Sdk/Scan/ScanController.cs:line 86
```

![image](https://user-images.githubusercontent.com/44505331/230742716-c09eaeba-9472-495a-a456-a5106001e291.png)

**To Reproduce**
1. in "Bit depth" select "Black and White"
2. Press "Scan"

**Expected behavior**

Scan successfully or give me an error I can do something with!

**Screenshots**

**Desktop (please complete the following information):**
 - OS: Ubuntu 22.04

```
$ flatpak info com.naps2.Naps2
NAPS2 - Not Another PDF Scanner - Scan documents to PDF and more, as simply as
possible.

          ID: com.naps2.Naps2
         Ref: app/com.naps2.Naps2/x86_64/beta
        Arch: x86_64
      Branch: beta
     Version: 7.0b7
     License: GPL-2.0-or-later
      Origin: naps2-origin
  Collection: 
Installation: user
   Installed: 72.9 MB
     Runtime: org.freedesktop.Platform/x86_64/22.08
         Sdk: org.freedesktop.Sdk/x86_64/22.08

      Commit: ef8d9f575f473dc663090f4e0c6a1ca36c2eea0b10bb26d9f3d2b06882fbea90
     Subject: Export com.naps2.Naps2
        Date: 2023-03-20 01:19:51 +0000
```

Same behaviour with the `deb` package

```
$ apt list | grep ^naps
naps2/now 7.0.7 amd64 [installed,local]
```

**Additional context**

"Grayscale" and "24-bit Color" both work

**Comment by xM8WVqaG** [comment]
Confirmed resolved in 7.0b8.
