### ISSUE TITLE
An error occured running OCR with LinuxMint 20.3 - Version 7.0b7

### ISSUE THREAD

**Issue by wassi007** [cyanfish/naps2#134]
**Describe the bug:**
OCR Error when scanning a document

**Error Message:**
An error occured running OCR

System.IO.FileNotFoundException: Could not find file '/home/juergen/.config/naps2/temp/nd243jjl.crc.hocr'.
File name: '/home/juergen/.config/naps2/temp/nd243jjl.crc.hocr'
   at Interop.ThrowExceptionForIoErrno(ErrorInfo , String , Boolean , Func`2 )
   at Interop.CheckIo(Error , String , Boolean , Func`2 )
   at Microsoft.Win32.SafeHandles.SafeFileHandle.Open(String , OpenFlags , Int32 )
   at Microsoft.Win32.SafeHandles.SafeFileHandle.Open(String , FileMode , FileAccess , FileShare , FileOptions , Int64 )
   at System.IO.Strategies.OSFileStreamStrategy..ctor(String , FileMode , FileAccess , FileShare , FileOptions , Int64 )
   at System.IO.Strategies.UnixFileStreamStrategy..ctor(String , FileMode , FileAccess , FileShare , FileOptions , Int64 )
   at System.IO.Strategies.FileStreamHelpers.ChooseStrategyCore(String , FileMode , FileAccess , FileShare , FileOptions , Int64 )
   at System.IO.Strategies.FileStreamHelpers.ChooseStrategy(FileStream , String , FileMode , FileAccess , FileShare , Int32 , FileOptions , Int64 )
   at System.IO.FileStream..ctor(String , FileMode , FileAccess , FileShare , Int32 , FileOptions , Int64 )
   at System.IO.FileStream..ctor(String , FileMode , FileAccess , FileShare , Int32 , FileOptions )
   at System.IO.FileStream..ctor(String , FileMode , FileAccess , FileShare , Int32 , Boolean )
   at System.IO.FileStream..ctor(String , FileMode , FileAccess , FileShare , Int32 )
   at System.Xml.XmlDownloadManager.GetStream(Uri , ICredentials , IWebProxy )
   at System.Xml.XmlUrlResolver.GetEntity(Uri , String , Type )
   at System.Xml.XmlTextReaderImpl.FinishInitUriString()
   at System.Xml.XmlTextReaderImpl..ctor(String , XmlReaderSettings , XmlParserContext , XmlResolver )
   at System.Xml.XmlReaderSettings.CreateReader(String , XmlParserContext )
   at System.Xml.XmlReader.Create(String , XmlReaderSettings , XmlParserContext )
   at System.Xml.XmlReader.Create(String , XmlReaderSettings )
   at System.Xml.Linq.XDocument.Load(String , LoadOptions )
   at System.Xml.Linq.XDocument.Load(String )
   at NAPS2.Ocr.TesseractOcrEngine.ProcessImage(String imagePath, OcrParams ocrParams, CancellationToken cancelToken) in /home/ben/naps2/NAPS2.Sdk/Ocr/TesseractOcrEngine.cs:line 97

**Reproduce:**
For every scan when OCR is on

**Desktop (please complete the following information):**
    OS: Linux Mint Cinnamon
    Version 20.3
    Package: Deb
    Version: 7.0b7

**Comment by cyanfish** [comment]
Please try [7.0b8](https://www.naps2.com/download), that should fix the issue.
