### ISSUE TITLE
7.x.x NAPS2.Worker.exe hangs with fujitsu 7460, 6.1.2 works fine

### ISSUE THREAD

**Issue by bani6809** [cyanfish/naps2#196]
**Describe the bug**
updated to 7.1.0, NAPS hangs on fujitsu 7460
revert to 6.1.2, scans work fine
tried 7.0b1, same problems repro.

**To Reproduce**
1. Fujitsu PaperStream IP fi-7460
2. If you have set to "use the native UI", NAPS hangs merely after opening and closing the fujitsu UI.
3. If you have set "Use predefined settings", NAPS hangs after the scan. If you click cancel, only one page of a double sided scan shows up.

**Expected behavior**
It should work like 6.1.2

**Screenshots**
![image](https://github.com/cyanfish/naps2/assets/43738861/e5e68627-c8bd-4ce7-aac3-8d4b3c71054e)

scanner says scan is finished.

![image](https://github.com/cyanfish/naps2/assets/43738861/b82d54a9-c470-4592-ab65-e182ab3910a2)

NAPS never completes, just hangs...

![image](https://github.com/cyanfish/naps2/assets/43738861/0065d17f-955e-43e9-93fa-7499f1112bd6)

if you hit cancel, only one side of a double sided scan shows up.

![image](https://github.com/cyanfish/naps2/assets/43738861/7b5fda29-ccb1-4400-a03d-9bd041cc4054)

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Version 7.1.0

**Additional context**
I did get NAPS2.Worker.exe to throw an exception and backtrace at least once, which may give a clue:
```
Status(StatusCode="Unavailable", Detail="failed to connec to all addresses")
Grpc.Core.RpcException: Status(StatusCode="Unavailable", Detail="failed to connect to all addresses")
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at GrpcDotNetNamedPipes.Internal.MessageReader`1.<MoveNext>d__5.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at NAPS2.Remoting.Worker.WorkerServiceAdapter.<TwainScan>d__11.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at NAPS2.Scan.Internal.Twain.RemoteTwainSessionController.<StartScan>d__3.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at NAPS2.Scan.Internal.Twain.TwainScanDriver.<Scan>d__3.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at NAPS2.Scan.Internal.RemoteScanController.<Scan>d__5.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at NAPS2.Scan.ScanController.<>c__DisplayClass10_0.<<Scan>b__6>
```

**Comment by cyanfish** [comment]
Can you follow the instructions [here](https://www.naps2.com/doc/troubleshooting#debug-log) to collect debug logs?

**Comment by Dimetr007** [comment]
Та же проблема с МФУ kyocera.
[debuglog.txt](https://github.com/cyanfish/naps2/files/13068334/debuglog.txt)
