### ISSUE TITLE
Could not start a worker process

### ISSUE THREAD

**Issue by naurahsopian** [cyanfish/naps2#262]
Describe the bug
After I run the naps2 application, a few seconds later it will close automatically, after I debug the error on "throw new InvalidOperationException("Could not start a worker process; see logs for details");"

To Reproduce
I am adding a module to send to dms application, there is an additional toolbar button.

![image](https://github.com/cyanfish/naps2/assets/86042962/0f65a43c-4550-4619-8abb-b6977b60ec9a)

Desktop (please complete the following information):

I'm using Windows 11 pro 64 bit and visual studio 2022.

**Comment by cyanfish** [comment]
Have you tried checking the [logs](https://www.naps2.com/doc/troubleshooting#error-log)?

**Comment by agiratech-magesh** [comment]
any fix on this ? help me out !

**Comment by fperie** [comment]
Hello @cyanfish and @agiratech-magesh,

With version 7.2.0 of NAPS2 for Windows x64, I am encountering a problem similar to @agiratech-magesh when I use `--listdevices` with the `twain` driver.

```
> NAPS2.Console.exe --version
NAPS2.Console 8.2.1+ff150dbe254988a12f4cadf23063dc85c5d60cbb
```

When the computer starts, the command works correctly, but after some time it fails because it cannot create a worker process:

```
> NAPS2.Console.exe --listdevices --driver "twain"

An unexpected error occurred.
Could not start a worker process; see logs for details
```

Here is the content of the `errorlog.txt` file:

```
2026-03-16 15:07:11.8626 20880 An error occurred that caused the console application to close. 
System.InvalidOperationException: Could not start a worker process; see logs for details
   at NAPS2.Remoting.Worker.WorkerFactory.NextWorker(ScanningContext scanningContext, WorkerType workerType)
   at NAPS2.Remoting.Worker.WorkerFactory.Create(ScanningContext scanningContext, WorkerType workerType)
   at NAPS2.Scan.ScanningContext.CreateWorker(WorkerType workerType)
   at NAPS2.Scan.Internal.Twain.RemoteTwainController.CreateWorker(ScanOptions options)
   at NAPS2.Scan.Internal.Twain.RemoteTwainController.GetDeviceList(ScanOptions options)
   at NAPS2.Scan.Internal.Twain.TwainScanDriver.<>c__DisplayClass2_0.<<GetDevices>b__0>d.MoveNext()
--- End of stack trace from previous location ---
   at NAPS2.Scan.Internal.RemoteScanController.GetDevices(ScanOptions options, CancellationToken cancelToken, Action`1 callback)
   at NAPS2.Scan.ScanController.<>c__DisplayClass12_0.<<GetDevices>b__0>d.MoveNext()
--- End of stack trace from previous location ---
   at NAPS2.Util.AsyncProducers.<>c__DisplayClass2_0`1.<<RunProducer>b__0>d.MoveNext()
   at async IAsyncEnumerable<T> NAPS2.Util.AsyncSink<T>.AsAsyncEnumerable()+MoveNext()
   at async Task NAPS2.Automation.AutomatedScanning.ListDevices() x 2
   at async Task NAPS2.Automation.AutomatedScanning.Execute()
```


Am I the only one experiencing this kind of issue?
Is there any workaround?
What could I do to resolve it?

Thanks for your help,
Fabien
