### ISSUE TITLE
SSL Connection could not be established 

### ISSUE THREAD

**Issue by min0me** [cyanfish/naps2#338]
**Describe the bug**
I am trying to scan a document using version 7.4.0 on Debian 12.5. I am using a HP LaserJet pro mfp m28w. I am able to find the device using the ESCL driver and set it up, however when I click the scan button i get an error: 

"The SSL connection could not be established, see inner exception"

System.Net.Http.HttpRequestException: The SSL connection could not be established, see inner exception.
 ---> System.Security.Authentication.AuthenticationException: Authentication failed, see inner exception.
 ---> Interop+OpenSsl+SslException: SSL Handshake failed with OpenSSL error - SSL_ERROR_SSL.
 ---> Interop+Crypto+OpenSslCryptographicException: error:0A000410:SSL routines::sslv3 alert handshake failure
   --- End of inner exception stack trace ---
   at SecurityStatusPalErrorCode Interop+OpenSsl.DoSslHandshake(SafeSslHandle, ReadOnlySpan<byte>, out byte[], out int)
   at SecurityStatusPal System.Net.Security.SslStreamPal.HandshakeInternal(ref SafeDeleteSslContext, ReadOnlySpan<byte>, ref byte[], SslAuthenticationOptions)
   --- End of inner exception stack trace ---
   at async Task System.Net.Security.SslStream.ForceAuthenticationAsync<TIOAdapter>(bool, byte[], CancellationToken)
   at async ValueTask<SslStream> System.Net.Http.ConnectHelper.EstablishSslConnectionAsync(SslClientAuthenticationOptions, HttpRequestMessage, bool, Stream, CancellationToken)
   --- End of inner exception stack trace ---
   at async ValueTask<SslStream> System.Net.Http.ConnectHelper.EstablishSslConnectionAsync(SslClientAuthenticationOptions, HttpRequestMessage, bool, Stream, CancellationToken)
   at async ValueTask<ValueTuple<Stream, TransportContext, IPEndPoint>> System.Net.Http.HttpConnectionPool.ConnectAsync(HttpRequestMessage, bool, CancellationToken)
   at async ValueTask<HttpConnection> System.Net.Http.HttpConnectionPool.CreateHttp11ConnectionAsync(HttpRequestMessage, bool, CancellationToken)
   at async Task System.Net.Http.HttpConnectionPool.AddHttp11ConnectionAsync(QueueItem)
   at async ValueTask<T> System.Threading.Tasks.TaskCompletionSourceWithCancellation<T>.WaitWithCancellationAsync(CancellationToken)
   at async ValueTask<HttpResponseMessage> System.Net.Http.HttpConnectionPool.SendWithVersionDetectionAndRetryAsync(HttpRequestMessage, bool, bool, CancellationToken)
   at async ValueTask<HttpResponseMessage> System.Net.Http.RedirectHandler.SendAsync(HttpRequestMessage, bool, CancellationToken)
   at async Task<HttpResponseMessage> System.Net.Http.HttpClient.SendAsync(HttpRequestMessage request)+Core(?)
   at async Task<XDocument> NAPS2.Escl.Client.EsclClient.DoRequest(string endpoint)
   at async Task<EsclCapabilities> NAPS2.Escl.Client.EsclClient.GetCapabilities()
   at async Task NAPS2.Scan.Internal.Escl.EsclScanDriver.Scan(ScanOptions options, CancellationToken cancelToken, IScanEvents scanEvents, Action<IMemoryImage> callback)
   at async Task NAPS2.Scan.Internal.RemoteScanController.Scan(ScanOptions options, CancellationToken cancelToken, IScanEvents scanEvents, Action<ProcessedImage, PostProcessingContext> callback)
   at async IAsyncEnumerable<ProcessedImage> NAPS2.Scan.ScanController.Scan(ScanOptions options, CancellationToken cancelToken)+(?) => { } 

I was originally using Debian 11 with naps2 7.3.1 which worked well. I did an update last week.

**To Reproduce**
Steps to reproduce the behaviour:
1. Click on scan
2. See error

**Expected behaviour**
I would be able to connect to the printer over the network and scan documents.

**Screenshots**

![image](https://github.com/cyanfish/naps2/assets/34134519/06cb4d2d-a98e-4bdc-b765-4d2aefed50fa)
![image](https://github.com/cyanfish/naps2/assets/34134519/05579bac-24ab-42c4-93fd-6cff3089b80d)

**Desktop (please complete the following information):**
 - OS: Debian 12.5 (bookworm)
 - Version 7.4.0

**Additional context**
Both devices are connected to the same access point.

**Comment by min0me** [comment]
Hi,

Ok that makes sense. I've never updated the printer since i got it (just encase HP decides to block 3rd party toner).

I tried sane-airscan, but it does not show. I will have a further dig around to see if i can get it to work.

Thanks for the reply and the work you are doing. 

Regards

**Comment by reinauer** [comment]
I am still seeing this with NAPS2 8.2.1.0. These printers often have self-signed certificates as you can't use Let's Encrypt and the sorts. Could that be the problem? I could not find an option to accept a self-signed certificate?

My Scanner (HP Color LaserJet MFP M477FDW) supports TLS 1.2
```
System.Net.Http.HttpRequestException: The SSL connection could not be established, see inner exception.
 ---> System.Security.Authentication.AuthenticationException: Authentication failed, see inner exception.
 ---> Interop+OpenSsl+SslException: SSL Handshake failed with OpenSSL error - SSL_ERROR_SSL.
 ---> Interop+Crypto+OpenSslCryptographicException: error:0A000410:SSL routines::ssl/tls alert handshake failure
   --- End of inner exception stack trace ---
   at Interop.OpenSsl.DoSslHandshake(SafeSslHandle context, ReadOnlySpan`1 input, ProtocolToken& token)
   at System.Net.Security.SslStreamPal.HandshakeInternal(SafeDeleteSslContext& context, ReadOnlySpan`1 inputBuffer, Int32& consumed, SslAuthenticationOptions sslAuthenticationOptions)
   --- End of inner exception stack trace ---
   at System.Net.Security.SslStream.ForceAuthenticationAsync[TIOAdapter](Boolean receiveFirst, Byte[] reAuthenticationData, CancellationToken cancellationToken)
   at System.Net.Http.ConnectHelper.EstablishSslConnectionAsyncCore(Stream stream, SslClientAuthenticationOptions sslOptions, CancellationToken cancellationToken) in C:\Projects\StandardSocketsHttpHandler\StandardSocketsHttpHandler\Net\Http\SocketsHttpHandler\ConnectHelper.cs:line 183
   --- End of inner exception stack trace ---
   at System.Net.Http.ConnectHelper.EstablishSslConnectionAsyncCore(Stream stream, SslClientAuthenticationOptions sslOptions, CancellationToken cancellationToken) in C:\Projects\StandardSocketsHttpHandler\StandardSocketsHttpHandler\Net\Http\SocketsHttpHandler\ConnectHelper.cs:line 194
   at System.Net.Http.HttpConnectionPool.CreateConnectionAsync(HttpRequestMessage request, CancellationToken cancellationToken) in C:\Projects\StandardSocketsHttpHandler\StandardSocketsHttpHandler\Net\Http\SocketsHttpHandler\HttpConnectionPool.cs:line 412
   at System.Net.Http.HttpConnectionPool.GetConnectionAsync(HttpRequestMessage request, CancellationToken cancellationToken) in C:\Projects\StandardSocketsHttpHandler\StandardSocketsHttpHandler\Net\Http\SocketsHttpHandler\HttpConnectionPool.cs:line 192
   at System.Net.Http.HttpConnectionPool.SendWithRetryAsync(HttpRequestMessage request, Boolean doRequestAuth, CancellationToken cancellationToken) in C:\Projects\StandardSocketsHttpHandler\StandardSocketsHttpHandler\Net\Http\SocketsHttpHandler\HttpConnectionPool.cs:line 292
   at System.Net.Http.RedirectHandler.SendAsync(HttpRequestMessage request, CancellationToken cancellationToken) in C:\Projects\StandardSocketsHttpHandler\StandardSocketsHttpHandler\Net\Http\SocketsHttpHandler\RedirectHandler.cs:line 67
   at System.Net.Http.HttpClient.<SendAsync>g__Core|83_0(HttpRequestMessage request, HttpCompletionOption completionOption, CancellationTokenSource cts, Boolean disposeCts, CancellationTokenSource pendingRequestsCts, CancellationToken originalCancellationToken)
   at NAPS2.Escl.Client.EsclClient.WithHttpFallback[T](Func`1 urlFunc, Func`2 func)
   at NAPS2.Escl.Client.EsclClient.DoRequest(String endpoint)
   at NAPS2.Escl.Client.EsclClient.GetCapabilities()
   at NAPS2.Scan.Internal.Escl.EsclScanDriver.GetEsclClientWithCaps(ScanOptions options, CancellationToken cancelToken, IScanEvents scanEvents)
   at NAPS2.Scan.Internal.Escl.EsclScanDriver.Scan(ScanOptions options, CancellationToken cancelToken, IScanEvents scanEvents, Action`1 callback)
   at NAPS2.Scan.Internal.RemoteScanController.Scan(ScanOptions options, CancellationToken cancelToken, IScanEvents scanEvents, Action`2 callback)
   at NAPS2.Scan.ScanController.<>c__DisplayClass15_1.<<Scan>g__DoScan|7>d.MoveNext()
--- End of stack trace from previous location ---
   at NAPS2.Scan.ScanController.<>c__DisplayClass15_0.<<Scan>b__6>d.MoveNext()
```
