### ISSUE TITLE
NAPS2 7.4.2 crashes when opened (KDE Arch Linux)

### ISSUE THREAD

**Issue by moritz1000** [cyanfish/naps2#373]
**Describe the bug**
NAPS2 crashes when trying to launch it.

**To Reproduce**
1. Open a terminal an type `naps2` (or open NAPS2 via shortcut)
2. See error

**Expected behavior**
NAPS2 opens without crashing.

**Screenshots**
![image](https://github.com/cyanfish/naps2/assets/35174351/91013034-7867-4219-8adf-8ad4731476a7)

**Desktop (please complete the following information):**
 - OS: KDE Arch Linux (Wayland)
 - Version: 7.4.2 (from the [AUR](https://aur.archlinux.org/packages/naps2-bin))

**Additional context**
I am sure that I was able to open and use NAPS2 yesterday so I am unsure if another package / dependency update broke it (since I am using rolling release distribution).

EDIT: So far I have tried reinstalling NAPS2 and removing `/home/username/.config/naps2`

```
❯ naps2
Unhandled exception. System.Reflection.TargetInvocationException: Exception has been thrown by the target of an invocation.
 ---> GLib.GException: Unrecognized image file format
   at Gdk.PixbufLoader.Write(Byte[] buf, UInt64 count)
   at Gdk.PixbufLoader.Write(Byte[] bytes, UInt32 count)
   at Gdk.PixbufLoader.LoadFromStream(Stream input)
   at Gdk.PixbufLoader.InitFromStream(Stream stream)
   at Gdk.PixbufLoader..ctor(Stream stream)
   at Gdk.Pixbuf..ctor(Stream stream)
   at Eto.GtkSharp.Drawing.IconHandler.Create(Stream stream)
   at Eto.Drawing.Icon..ctor(Stream stream)
   at NAPS2.EtoForms.EtoExtensions.ToEtoIcon(Byte[] bytes)
   at NAPS2.EtoForms.Ui.DesktopForm.BuildLayout()
   at NAPS2.EtoForms.EtoFormBase.OnPreLoad(EventArgs e)
   at Eto.Forms.Form.Show()
   at Eto.Forms.Application.<>c__DisplayClass63_0.<Run>b__0(Object sender, EventArgs e)
   at Eto.PropertyStore.TriggerEvent[T](Object key, Object sender, T args)
   at Eto.Forms.Application.OnInitialized(EventArgs e)
   at Eto.Forms.Application.Callback.OnInitialized(Application widget, EventArgs e)
   at Eto.GtkSharp.Forms.ApplicationHandler.Run()
   at Eto.Forms.Application.Run(Form mainForm)
   at NAPS2.EntryPoints.GuiEntryPoint.Run(String[] args, Module imageModule, Module guiModule)
   at NAPS2.EntryPoints.GtkEntryPoint.Run(String[] args)
   at System.RuntimeMethodHandle.InvokeMethod(Object, Void**, Signature, Boolean)
   at System.Reflection.MethodBaseInvoker.InterpretedInvoke_Method(Object obj, IntPtr* args)
   at System.Reflection.MethodBaseInvoker.InvokeDirectByRefWithFewArgs(Object, Span`1, BindingFlags)
   --- End of inner exception stack trace ---
   at System.Reflection.MethodBaseInvoker.InvokeDirectByRefWithFewArgs(Object, Span`1, BindingFlags)
   at System.Reflection.MethodBaseInvoker.InvokeWithOneArg(Object, BindingFlags, Binder, Object[], CultureInfo)
   at System.Reflection.RuntimeMethodInfo.Invoke(Object, BindingFlags, Binder, Object[], CultureInfo)
   at System.Reflection.MethodBase.Invoke(Object obj, Object[] parameters)
   at NAPS2.Program.Main(String[] args)
fish: Job 1, 'naps2' terminated by signal SIGABRT (Abort)

~ 
❯ 
```

**Comment by moritz1000** [comment]
I don't know if this core dump(?) helps:
```
❯ coredumpctl list
[...]
Sat 2024-04-20 15:00:26 CEST 13742 1000 1000 SIGABRT present  /usr/lib/naps2/naps2                      7.8M
❯ coredumpctl info 13742
```

[coredumpctl_info_13742.txt](https://github.com/cyanfish/naps2/files/15048323/coredumpctl_info_13742.txt)

**Comment by moritz1000** [comment]
So the problem had to do with `gdk-pixbuf2` I guess:
An update just arrived: https://gitlab.archlinux.org/archlinux/packaging/packages/gdk-pixbuf2/-/commits/main 
and now everything works again.

Oh the joy or running a rolling release distro :cry:.
