### ISSUE TITLE
7.0b2 Importing recently saved document fails via drag/drop

### ISSUE THREAD

**Issue by jcurl** [cyanfish/naps2#49]
**Describe the bug**
Scanned in a document using NAPS2 7.0b2. Saved it as a normal PDF. Importing the document by drag and drop results in an exception that it could not be imported.

**To Reproduce**
1. Scan in a document, save it. e.g. foobär.pdf
2. Drag and drop the saved PDF into a new instance of NAPS2 7.0b2
3. See error
```
System.IO.FileNotFoundException: Could not find pdf file: 'C:/Users/jcurl/Documents/foob%C3%A4r.pdf'
   at NAPS2.ImportExport.Pdf.PdfImporter.LoadDocument(String filePath, ImportParams importParams)
   at NAPS2.ImportExport.Pdf.PdfImporter.<>c__DisplayClass7_0.<Import>b__0(Action`1 produceImage)
   at NAPS2.Util.AsyncProducers.<>c__DisplayClass0_0`1.<RunProducer>b__0(Action`1 produce)
   at NAPS2.Util.AsyncProducers.<>c__DisplayClass1_0`1.<<RunProducer>b__0>d.MoveNext()
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at NAPS2.Util.AsyncSink`1.<AsAsyncEnumerable>d__3.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Threading.Tasks.Sources.ManualResetValueTaskSourceCore`1.GetResult(Int16 token)
   at NAPS2.ImportExport.ImportOperation.<>c__DisplayClass2_0.<<Start>b__0>d.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at NAPS2.ImportExport.ImportOperation.<>c__DisplayClass2_0.<<Start>b__0>d.MoveNext()
```

**Expected behavior**
The file name on import shouldn't be munged under Windows (UTF16, not UTF8)

**Screenshots**
None applicable.

**Desktop (please complete the following information):**
 - Windows 10.19043 64-bit

**Additional context**
None.

**Comment by cyanfish** [comment]
Thanks, this should be fixed in [7.0b3](https://www.naps2.com/download).
