### ISSUE TITLE
7.0b4 - Can't import PDFs

### ISSUE THREAD

**Issue by srdlgh** [cyanfish/naps2#79]
Either by icon or by drop, can't import PDFs -- even those created by NAPS2.

Error message is:

System.NotSupportedException: Unsupported file format: Unspecified
   at NAPS2.Images.ImageContext.CheckSupportsFormat(ImageFileFormat format) in /run/build/main/NAPS2.Images/ImageContext.cs:line 250
   at NAPS2.Images.ImageContext.DoLoadFrames(Stream stream, ImageFileFormat format, ProgressHandler progress, Boolean disposeStream) in /run/build/main/NAPS2.Images/ImageContext.cs:line 206
   at NAPS2.ImportExport.Images.ImageImporter.<>c__DisplayClass4_0.<<Import>b__0>d.MoveNext() in /run/build/main/NAPS2.Sdk/ImportExport/Images/ImageImporter.cs:line 29
--- End of stack trace from previous location ---
   at NAPS2.Util.AsyncProducers.<>c__DisplayClass1_0`1.<<RunProducer>b__0>d.MoveNext() in /run/build/main/NAPS2.Images/Util/AsyncProducers.cs:line 22
   at NAPS2.Util.AsyncSink`1.AsAsyncEnumerable()+MoveNext()
   at NAPS2.Util.AsyncSink`1.AsAsyncEnumerable()+System.Threading.Tasks.Sources.IValueTaskSource<System.Boolean>.GetResult()
   at NAPS2.ImportExport.ImportOperation.<>c__DisplayClass2_0.<<Start>b__0>d.MoveNext() in /run/build/main/NAPS2.Lib/ImportExport/ImportOperation.cs:line 35
--- End of stack trace from previous location ---
   at NAPS2.ImportExport.ImportOperation.<>c__DisplayClass2_0.<<Start>b__0>d.MoveNext() in /run/build/main/NAPS2.Lib/ImportExport/ImportOperation.cs:line 35

**Comment by cyanfish** [comment]
This should be fixed in the latest [beta version](https://www.naps2.com/download) (7.0b5). There were two separate issues, one with non-naps2 pdfs and one with files without extensions.
